version: '3.3'

services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: crud-nginx
    environment:
        - VIRTUAL_HOST=crud.andrewkozinsky.ru
        - LETSENCRYPT_HOST=crud.andrewkozinsky.ru
    depends_on:
      - api
      - db
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf

  api:
    build:
      context: api
      dockerfile: Dockerfile.prod
    container_name: crud-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: bxspozdFS46
      JWT_EXPIRE: 1800
    depends_on:
      - db
    command: npm run start:prod

  db:
    image: postgres:13-alpine
    container_name: crud-db
    restart: unless-stopped
    ports:
      - "4000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kxPQgs_35Qq
      POSTGRES_DB: crud
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
